version: '3'

services:
  product-service:
    container_name: product-service
    build:
      context: .
    restart: on-failure
    ports:
      - 8081:8080
    environment:
      - spring.datasource.url=jdbc:postgresql://product-db:5432/product

networks:
  default:
    external:
      name: product-app
